### PR TITLE
Change libblas to libblastrampoline

### PR DESCRIPTION
**Pull request by theabhirath**
Xref https://github.com/JuliaLang/julia/pull/44360, `libblas` is not used anymore for Julia v1.9 and above, and `libblastrampoline` is instead. Causing errors for CI on Julia master including places like https://github.com/FluxML/Metalhead.jl/pull/125#issuecomment-1055716157

### CODE REVIEW

File: src/gemm.jl [hunk 1]
```diff
@@ -2,7 +2,14 @@
 ## Borrowed from Knet.jl, adapted for compile-time constants
 
 using LinearAlgebra
-using LinearAlgebra.BLAS: libblastrampoline, BlasInt, @blasfunc
+using LinearAlgebra.BLAS: BlasInt, @blasfunc
+
+if VERSION >= v"1.7-"
+    using LinearAlgebra.BLAS: libblastrampoline
+    libblas = libblastrampoline
```
Comment (ToucheSir) [inline src/gemm.jl:9]: Does this need to be `const`? I don't recall if that helps inside of modules, but other aliases in NNib use it.

Comment (theabhirath) [reply src/gemm.jl:9]: Yeah the original implementation does use `const` - I dropped that because the linter becomes upset (`Invalid redefinition of constant.`) but could always put it back

**Comment by IanButterworth** [comment]
@ViralBShah what's the right thing to do here?

File: src/gemm.jl [hunk 2]
```diff
@@ -2,7 +2,14 @@
 ## Borrowed from Knet.jl, adapted for compile-time constants
 
 using LinearAlgebra
-using LinearAlgebra.BLAS: libblas, BlasInt, @blasfunc
+using LinearAlgebra.BLAS: BlasInt, @blasfunc
+
+if VERSION >= v"1.7-"
```
[the remark this answers is not in the document]
Comment (theabhirath) [reply src/gemm.jl]: This seems to be causing an error somehow?

**Comment by ViralBShah** [comment]
You can use `Base.libblas_name` (merged last night in a follow-on PR) which now points to `libblastrampoline`. That will work with 1.6 as well as older releases.

File: src/gemm.jl (hunk 2 above)
[the remark this answers is not in the document]
Comment (ViralBShah) [reply src/gemm.jl]: Updated this PR with something that avoids this altogether.

**Comment by IanButterworth** [comment]
Seems like there's an exported name clash? or is `libblas` imported in another file?

**Comment by ViralBShah** [comment]
We'll need to wait for another day or so for the new nightlies. I think should go through at that point.

**Comment by ViralBShah** [comment]
We need a new nightly to come out today that should make this work.

**Comment by ViralBShah** [comment]
Linux nightly binaries are unfortunately a bit behind - and we'll have them shortly. This should fix the issue though.
